name = "MolecularTopologies"
uuid = "a207b480-8fe6-11e8-0ddf-8f5d92e52f2c"
authors = ["Tom Lee <contact@tomlee.com.au>"]
version = "1.1.0-DEV"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
